# Generated by Django 5.2.10 on 2026-01-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_reyting_product_remove_reyting_user_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
