# Generated by Django 5.2.10 on 2026-01-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_review_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
